//! Workspace smoke test — auto-generated by caixa-forge.
//! Keeps `cargo test` green at the workspace root so the
//! auto-release pipeline's pre-merge-gate passes by default.

#[test]
fn workspace_smoke() {
    assert_eq!(2 + 2, 4);
}
